name: Job Scraper Workflow

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:        # Allows manual trigger from GitHub UI
  push:
    paths:
      - 'job_scraper.py'   # Run when job_scraper.py is modified
      - 'greenhouse_scraper.py'  # Run when greenhouse_scraper.py is modified
      - '.github/workflows/job_scraper.yml'  # Run when workflow file is modified

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create Firebase credentials file
      run: |
        echo "${{ secrets.FIREBASE_CREDENTIALS_JSON }}" > firebase_credentials.json
      
    - name: Run job scraper
      env:
        FIREBASE_CREDENTIALS_PATH: 'firebase_credentials.json'
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python job_scraper.py
        
    - name: Clean up credentials
      if: always()  # Run even if previous steps fail
      run: |
        rm -f firebase_credentials.json 