name: Job Scraper Workflow

on:
  schedule:
    - cron: '0 4,10,16,22 * * *' 
    # Runs every 6 hours starting 8 AM PST
    #2 AM PST = 10:00 UTC
    # 8 AM PST = 16:00 UTC
    # 2 PM PST = 22:00 UTC
    # 8 PM PST = 04:00 UTC
  workflow_dispatch:        # Allows manual trigger from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create Firebase credentials file
      run: |
        echo "${{ secrets.FIREBASE_CREDENTIALS_JSON }}" > firebase_credentials.json
      
    - name: Run job scraper
      env:
        FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python job_scraper.py
        
    - name: Clean up credentials
      if: always()  # Run even if previous steps fail
      run: |
        rm -f firebase_credentials.json 